modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      fail_if_not_ssl: false

  http_tls:
    prober: http
    http:
      tls_config:
        insecure_skip_verify: true

  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"

  tcp_connect:
    prober: tcp
